apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels: 
    app: mydeploylabel
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mydeploylabel
  template:
    metadata:
      labels:
        app: mydeploylabel
    spec:
      containers:
        - name: myapp
          image: nginx
          volumeMounts:
          - name: myvolume
            mountPath: /usr/share/nginx/html/
            readOnly: true
      volumes:
        - name: myvolume
          configMap:
            name: myindex
