apiVersion: v1
kind: Service
metadata:
  labels:
    app: mydeploylabel
  name: mydeployment
spec:
  ports:
  - port: 8080
  protocol: TCP
  targetPort: 80
  selector:
    app: mydeploylabel
  type: ClusterIP

