name: Continuous Integration Kubernetes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  kubernetes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: kubectl setup | Kubernetes CLI
      uses: ghostzero/kubectl@v1